name: onlinica
description: onlinica app
version: 1.1.1+1

environment:
  sdk: '>=3.0.5 <4.0.0'

#  Platform  Firebase App Id
#  android   1:765672120056:android:42d547c4f0564748d0250d
#  ios       1:765672120056:ios:eec3ac0dfbff955ed0250d

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_lints: ^2.0.0
  go_router: ^11.1.2
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  cached_network_image: ^3.3.0
  flutter_statusbarcolor_ns: ^0.5.0
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.1.11
  shared_preferences: ^2.1.1
  flutter_svg: 1.1.6
  auto_size_text: ^3.0.0
  flutter_svg_provider: ^1.0.3
  image_picker: ^1.0.4
  intl:
  stream_mixin: ^3.0.4
  firebase_core: ^2.14.0
  pull_to_refresh: ^2.0.0
  firebase_messaging:
  flutter_local_notifications: ^15.0.0
  device_info_plus: ^9.0.2
  package_info_plus: ^4.0.2
  permission_handler: ^10.4.1
  google_sign_in: 6.1.4
#  flutter_facebook_auth: 5.0.11
  firebase_auth: ^4.9.0
  sign_button: ^2.0.6
  webview_flutter: ^4.2.0
  flutter_easyloading: ^3.0.5
  shimmer: ^3.0.0
  version: ^3.0.2
  flutter_facebook_auth: ^3.5.0
  flutter_localizations:
    sdk: flutter
  video_player: 2.7.2
  flutter_inappwebview_internal_annotations: ^1.1.1
  flutter_inappwebview: ^5.8.0
  flutter_widget_from_html:  0.9.1
  http_parser: ^4.0.2
  flutter_image_compress: ^2.1.0
  image_gallery_saver: ^2.0.3
  photo_view: ^0.14.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


#flutter_launcher_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/images/logo.jpg"
#  min_sdk_android: 21


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: SVN-Product Sans
      fonts:
        - asset: assets/fonts/SVNProductSans.ttf
          weight: 400
        - asset: assets/fonts/SVNProductSansBold.ttf
          weight: 700
        - asset: assets/fonts/SVNProductSansItalic.ttf
          weight: 400
        - asset: assets/fonts/SVNProductSansBoldItalic.ttf
          weight: 700